export type BlogPost = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  keyword: string;
  category: 'Trends' | 'Beginner' | 'Colour' | 'Shapes' | 'Techniques';
  sourceName: string;
  sourceUrl: string;
  image: number;
  ideas: { name: string; detail: string }[];
  salonBrief: string;
  note: string;
};

const post = (
  slug: string, title: string, keyword: string, category: BlogPost['category'], description: string,
  sourceName: string, sourceUrl: string, image: number, ideas: [string, string][], salonBrief: string, note: string,
): BlogPost => ({
  slug, title, keyword, category, description, sourceName, sourceUrl, image, salonBrief, note,
  seoTitle: `${title} | NailMuse UK`,
  ideas: ideas.map(([name, detail]) => ({ name, detail })),
});

export const blogPublished = '2026-09-27';

export const blogPosts: BlogPost[] = [
  post('new-nail-art-designs-uk', 'New Nail Art Designs: The UK Edit', 'nail art designs', 'Trends', 'A practical edit of the newest nail art designs, translated into colours, finishes and salon-ready wording for UK appointments.', 'British Vogue', 'https://www.vogue.co.uk/article/nail-trends-2026', 0,
    [['Velvet cat-eye', 'Ask for fine magnetic pigment diffused into a soft glow rather than a hard stripe.'], ['Micro details', 'Tiny dots, stars and fine lines add interest without crowding a short nail.'], ['Modern plaid', 'Keep checks fine and repeat only two or three colours across the set.'], ['Sheer layers', 'Translucent pink, spice and grey make regrowth less obvious.'], ['Sculpted almond', 'Use the tapered shape to frame chrome, French and tonal designs.']],
    'Bring one reference and name the shape, base colour, finish and detail placement you want.', 'Trend signals change quickly, so this edit is reviewed against current UK reporting.'),
  post('autumn-nail-art-designs', 'Autumn Nail Art Designs for the UK', 'autumn nail art designs', 'Trends', 'Wearable ideas for the shift from early September warmth to darker bonfire-season manicures.', 'Glamour UK', 'https://www.glamourmagazine.co.uk/gallery/autumn-nail-designs', 1,
    [['Sheer spice', 'A transparent cinnamon wash feels lighter than opaque brown.'], ['Burgundy gloss', 'A short, immaculate shape keeps deep wine colour polished.'], ['Tortoiseshell', 'Use amber, caramel and irregular dark markings for depth.'], ['Fine plaid', 'Oxblood, navy and cream create a neat heritage check.'], ['Gilded navy', 'One narrow gold detail lifts an inky blue base.']],
    'Ask for one autumn colour family, one finish and no more than one statement motif.', 'Daylight reveals undertones more accurately than salon lighting.'),
  post('winter-nail-art-designs', 'Winter Nail Art Designs Beyond Christmas', 'winter nail art designs', 'Trends', 'Cold-weather manicures in navy, smoky lilac, chocolate and icy sheer finishes that still work after December.', 'British Vogue', 'https://www.vogue.co.uk/article/nail-colour-trends-2026', 2,
    [['Midnight velvet', 'Magnetic navy catches winter light without loose glitter.'], ['Smoky amethyst', 'Greyed purple is softer than black but still dramatic.'], ['Icy micro-French', 'A translucent base with a silver-white edge suits short nails.'], ['Chocolate chrome', 'Warm brown gains dimension with a restrained metallic sheen.'], ['Oyster grey', 'Choose a pearly grey rather than a flat cement tone.']],
    'Request a cool-season shade in a glossy, pearly or velvet finish and keep art minimal.', 'Protect polish during cleaning and wet work with gloves.'),
  post('spring-nail-art-designs', 'Spring Nail Art Designs', 'spring nail art designs', 'Trends', 'Pastel gingham, miniature flowers and fresh milky colour for brighter UK spring days.', 'Who What Wear UK', 'https://www.whowhatwear.com/uk/beauty/nails/dated-nail-trends-spring-2026', 3,
    [['Pastel gingham', 'Fine crossing lines look cleanest on one or two accent nails.'], ['Micro daisies', 'Five small dots and a contrasting centre make an easy flower.'], ['Milky lavender', 'A translucent lilac wash keeps the effect airy.'], ['Polka dots', 'Even spacing feels neat; irregular spacing feels playful.'], ['Coloured micro-French', 'Rotate pastel tips over one consistent sheer base.']],
    'Choose two pastels plus one neutral so a mixed spring set remains cohesive.', 'Let regular polish dry fully between layers to prevent dragging.'),
  post('summer-nail-art-designs-uk', 'Summer Nail Art Designs for Holidays and Home', 'summer nail art designs', 'Trends', 'Bright but wearable summer ideas, from fruit-tinted jelly colour to washed denim and miniature citrus.', 'Who What Wear', 'https://www.whowhatwear.com/beauty/nails/summer-nail-trends-2026', 4,
    [['Fruit-water tints', 'Transparent orange, cherry and grape shades look juicy rather than heavy.'], ['Washed denim', 'A softened mid-blue pairs well with white details.'], ['Tiny citrus', 'Keep fruit motifs to one accent nail or a few small slices.'], ['Pistachio tips', 'A green micro-French is colourful but easy to wear.'], ['Soft ombré', 'Blend two related shades for a lower-contrast gradient.']],
    'Tell your technician about swimming, travel and expected wear so the service suits the trip.', 'Book removal rather than picking off enhancement products.'),
  post('christmas-nail-art-designs', 'Christmas Nail Art Designs You Can Actually Wear', 'Christmas nail art designs', 'Trends', 'Festive designs ranging from one fine gold star to ruby French tips and full party-season sparkle.', 'British Vogue', 'https://www.vogue.co.uk/article/christmas-nail-designs', 5,
    [['Ruby French', 'Swap the classic white edge for glossy festive red.'], ['Tiny gold stars', 'Use different sizes but keep placement sparse.'], ['Velvet ribbon', 'A narrow painted curve nods to gift ribbon without becoming novelty art.'], ['Pearl shimmer', 'A translucent glow works for minimalists and formal events.'], ['Mulled wine', 'Deep burgundy is festive even without added art.']],
    'Ask for one festive cue—colour, metallic finish or motif—then keep the remaining elements simple.', 'Cuticle oil and gloves for cleaning help a party manicure look fresh.'),
  post('beginners-nail-art-designs', 'Beginner Nail Art Designs: 25 Easy Ideas', 'beginners nail art designs', 'Beginner', 'Simple designs organised by tool, time and difficulty so first attempts feel achievable.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/polka-dot-nail-guide-mii-cosmetics/', 6,
    [['Single dots', 'Place one dot near the cuticle on each dry base coat.'], ['Bottle-brush stripe', 'Wipe most polish from the brush before making one loose stroke.'], ['Tape diagonal', 'Remove low-tack tape before the top layer fully sets.'], ['Accent nail', 'Practise the detailed design on one nail and keep the rest plain.'], ['Dot flowers', 'Arrange five dots around a contrasting centre.']],
    'Start with regular polish, a limited palette and one repeatable mark.', 'Small irregularities are less visible in scattered or intentionally varied patterns.'),
  post('nail-art-tools-for-beginners', 'Nail Art Tools for Beginners', 'nail art tools for beginners', 'Beginner', 'A no-waste starter kit explaining what each tool does and which purchases can wait.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/simple-speedy-steps-floral-nail-art/', 7,
    [['Dotting tool', 'Useful for dots, flowers, eyes and small rounded details.'], ['Fine liner', 'Creates thin curves, checks, outlines and micro tips.'], ['Clean-up brush', 'A small angled brush sharpens edges with remover.'], ['Low-tack tape', 'Helps create blocks and straight diagonals on fully dry polish.'], ['Top coat', 'Smooths minor texture and protects the finished design.']],
    'Buy one dotting tool and one fine liner before investing in a large brush set.', 'Clean tools between colours and follow every product manufacturer’s directions.'),
  post('how-to-do-dot-nail-art', 'How to Do Dot Nail Art', 'dot nail art', 'Beginner', 'A straightforward method for clean polka dots, daisy petals and dotted French tips.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/polka-dot-nail-guide-mii-cosmetics/', 8,
    [['Prepare', 'Apply base colour and allow regular polish to dry.'], ['Load lightly', 'Place a small polish pool on a palette and dip only the tool tip.'], ['Place vertically', 'Touch down gently without dragging the dot.'], ['Reload often', 'Dot size shrinks as product leaves the tool.'], ['Seal carefully', 'Float top coat over dry dots to avoid smearing.']],
    'For even dots, use one tool end, similar pressure and a simple spacing guide.', 'Practise on foil or a nail wheel before working on your hand.'),
  post('easy-nail-art-without-tools', 'Easy Nail Art Without Specialist Tools', 'easy nail art without tools', 'Beginner', 'Low-risk ideas made with the bottle brush, clean cosmetic sponge and low-tack tape.', 'Woman & Home', 'https://www.womanandhome.com/beauty/simple-summer-nails/', 9,
    [['Dry-brush texture', 'Remove most polish and skim colour lightly across a dry base.'], ['Sponge gradient', 'Use a clean cosmetic sponge to press two overlapping colours.'], ['Tape blocks', 'Create a diagonal or half-and-half design on completely dry polish.'], ['Loose swirls', 'Use the corner of the bottle brush for an intentionally organic line.'], ['Glitter fade', 'Concentrate glitter near the tip and reduce it towards the cuticle.']],
    'Choose forgiving abstract designs rather than trying to reproduce intricate salon art.', 'Use only clean, blunt household substitutes; do not place sharp objects under nails.'),
  post('how-to-do-nail-art-at-home', 'How to Do Nail Art at Home Safely', 'how to do nail art at home', 'Beginner', 'A complete regular-polish workflow with clear boundaries around gel systems and allergy risk.', 'British Association of Dermatologists', 'https://www.bad.org.uk/dermatologists-issue-warning-about-uk-artificial-nail-allergy-epidemic', 10,
    [['Set up', 'Work in a ventilated area with stable lighting and a protected surface.'], ['Prepare gently', 'Shape the free edge and remove surface oils without cutting living skin.'], ['Work thinly', 'Two thin colour coats usually dry more evenly than one thick coat.'], ['Keep skin clean', 'Remove accidental polish promptly and avoid uncured enhancement product on skin.'], ['Remove properly', 'Follow the product system instead of peeling or scraping.']],
    'For gel or acrylic services, use a trained technician and ask about the matched product and lamp system.', 'Stop using a product and seek qualified advice if you develop redness, swelling, itching or nail separation.'),
  post('easy-nail-art-designs-for-toenails', 'Easy Nail Art Designs for Toenails', 'easy nail art designs for toenails', 'Beginner', 'Toe-scale ideas with clear big-toe accents, colour pairings and practical drying advice.', 'Marie Claire UK', 'https://www.marieclaire.co.uk/beauty/summer-pedicure-colours', 11,
    [['Big-toe flower', 'Keep the smaller toes in one block colour.'], ['Micro-French', 'A narrow edge looks clean and works with sandals.'], ['Two-colour dots', 'Place a short dotted line on the big toe only.'], ['Rainbow set', 'Use one colour per toe rather than tiny complex motifs.'], ['Matching accent', 'Repeat one manicure colour on the pedicure for cohesion.']],
    'Choose one readable big-toe motif and one supporting colour for the remaining nails.', 'Trim toenails straight across and allow plenty of drying time before closed shoes.'),
  post('rainbow-nail-art-designs', 'Rainbow Nail Art Designs for Every Nail Length', 'rainbow nail art designs', 'Colour', 'Modern rainbow manicures from subtle micro tips to bright gradients, each adaptable to short nails.', 'The Nailasaurus', 'https://www.thenailasaurus.com/2014/09/31-day-challenge-rainbow-nails.html', 12,
    [['Micro-rainbow tips', 'Divide a fine tip into small colour sections.'], ['Tonal rainbow', 'Use related muted shades for a softer spectrum.'], ['Negative-space arcs', 'Paint one curved rainbow on an otherwise sheer nail.'], ['One shade per nail', 'The easiest route to a clean multicolour set.'], ['Sponge gradient', 'Overlap neighbouring colours gently to avoid muddy transitions.']],
    'Decide whether you want bright, pastel or muted colour before choosing the five-shade palette.', 'A consistent base and finish keep multiple colours looking intentional.'),
  post('chrome-nail-art-designs', 'Chrome Nail Art Designs: Pearl to Mirror', 'chrome nail art designs', 'Colour', 'A visual guide to pearl, glazed, coloured and mirror chrome with useful salon vocabulary.', 'British Vogue', 'https://www.vogue.co.uk/article/nail-trends-2026', 13,
    [['Pearl glaze', 'A translucent white sheen lets the base colour influence the result.'], ['Silver mirror', 'An opaque reflective finish makes the strongest statement.'], ['Pink chrome', 'A rosy base warms the metallic layer.'], ['Chrome French', 'Metallic powder is contained at the tip for a lighter look.'], ['Isolated accent', 'One chrome curve or panel adds shine without covering every nail.']],
    'Show the desired reflectiveness and base colour; “chrome” alone can describe very different finishes.', 'Ask how the chosen system should be removed and maintained.'),
  post('pink-nail-art-designs', 'Pink Nail Art Designs That Do Not All Look the Same', 'pink nail art designs', 'Colour', 'Pink manicures organised by undertone, depth, finish and occasion rather than one repetitive gallery.', 'Who What Wear UK', 'https://www.whowhatwear.com/uk/invisible-nail-trend', 14,
    [['Barely-there blush', 'A sheer pink visually tidies the nail while leaving it visible.'], ['Dusty rose', 'A muted tone works well for autumn and office settings.'], ['Bubblegum dots', 'A vivid pink detail lifts a neutral base.'], ['Magenta French', 'Strong colour stays controlled when limited to the edge.'], ['Pearl pink', 'Fine shimmer gives a softer alternative to mirror chrome.']],
    'Compare a polish swatch with your skin in daylight and choose warm, cool or neutral pink accordingly.', 'Undertone guidance is a starting point, not a rule—wear the colour you enjoy.'),
  post('red-nail-art-designs', 'Red Nail Art Designs: Classic, Cherry and Wine', 'red nail art designs', 'Colour', 'Red designs arranged from bright tomato to deep burgundy, with understated and statement options.', 'Glamour UK', 'https://www.glamourmagazine.co.uk/gallery/autumn-nail-designs', 15,
    [['Tomato gloss', 'An orange-red feels especially lively in summer.'], ['Cherry detail', 'Paint a tiny fruit accent over a sheer neutral.'], ['Ruby French', 'A fine red tip works for events and shorter lengths.'], ['Wine half-moon', 'Leave a clean crescent of base visible near the cuticle.'], ['Oxblood short nails', 'A neat compact shape balances the dark colour.']],
    'Name the undertone—orange, true, blue-red or brown-red—before discussing art.', 'Dark saturated colour can stain, so use an appropriate base coat.'),
  post('blue-nail-art-designs', 'Blue Nail Art Designs: Denim to Midnight', 'blue nail art designs', 'Colour', 'Blue manicures spanning powder, denim, cobalt, ocean and inky navy finishes.', 'British Vogue', 'https://www.vogue.co.uk/article/nail-colour-trends-2026', 16,
    [['Powder micro-French', 'A soft blue edge gives a subtle spring update.'], ['Washed denim', 'A muted mid-blue feels casual and modern.'], ['Cobalt block', 'One vivid accent nail creates focus.'], ['Watery jelly', 'Translucent ocean colour builds depth in thin layers.'], ['Midnight gold', 'A narrow metallic detail warms deep navy.']],
    'Choose lightness and undertone first, then decide between cream, jelly, shimmer or velvet finish.', 'Deep blues look most intentional with a clean cuticle line.'),
  post('floral-nail-art-designs', 'Floral Nail Art: Daisies to Milk-Bath Petals', 'floral nail art designs', 'Colour', 'Flower designs from beginner dots to translucent layered petals and fine botanical lines.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/simple-speedy-steps-floral-nail-art/', 17,
    [['Dot daisies', 'Five dots around a centre create the simplest recognisable flower.'], ['Micro botanicals', 'Fine stems and two-leaf shapes suit compact nails.'], ['Milk-bath petals', 'Layer soft petals between translucent colour coats.'], ['French florals', 'Place tiny blooms along part of the tip.'], ['Bridal white flowers', 'Use low-contrast petals over a milky base.']],
    'Pick the flower scale and placement to fit your actual nail length.', 'For regular polish, allow each layer to dry before adding translucent colour.'),
  post('nail-art-designs-for-short-nails', 'Nail Art Designs for Short Nails', 'nail art designs for short nails', 'Shapes', 'Space-smart manicures selected for short nail plates, with useful shape and placement guidance.', 'British Vogue', 'https://www.vogue.co.uk/article/short-nails-ideas', 18,
    [['Micro-French', 'A narrow line follows the free edge without shortening the nail visually.'], ['Vertical accent', 'One fine line can create a lengthening direction.'], ['Side detail', 'A small off-centre motif leaves useful negative space.'], ['Half-moon', 'Detail near the cuticle preserves a clean tip.'], ['Tiny dots', 'Scale the motif down instead of squeezing in a large design.']],
    'Ask your technician to adapt the reference rather than copying artwork designed for long extensions.', 'Round, oval and squoval are practical options; the natural nail plate should guide the choice.'),
  post('almond-nail-art-designs', 'Almond Nail Art Designs and Shape Guide', 'almond nail art designs', 'Shapes', 'Designs that follow a tapered almond silhouette, with realistic length and maintenance notes.', 'British Vogue', 'https://www.vogue.co.uk/article/nail-trends-2026', 19,
    [['Contour French', 'Follow the tapered perimeter to emphasise the shape.'], ['Velvet cat-eye', 'A central glow complements the elongated silhouette.'], ['Pearl chrome', 'A smooth reflective finish shows the curve of the nail.'], ['Botanical line', 'A slim stem works with the vertical space.'], ['Soft aura', 'A diffused centre keeps longer nails visually balanced.']],
    'Confirm whether your natural length can support almond or whether an enhancement is needed.', 'Almond requires enough free edge to create a proportional taper.'),
  post('square-squoval-nail-art-designs', 'Square and Squoval Nail Art Designs', 'square nail art designs', 'Shapes', 'A practical comparison of square and softened squoval shapes with designs that complement each.', 'British Vogue', 'https://www.vogue.co.uk/article/short-nails-ideas', 20,
    [['Grid lines', 'Straight checks echo a square free edge.'], ['Side French', 'A diagonal corner detail softens the geometry.'], ['Centred dots', 'Simple alignment gives structure without extra width.'], ['Colour blocks', 'Use vertical divisions when you want a lengthening effect.'], ['Soft chrome', 'A uniform sheen lets the shape remain the focus.']],
    'Ask for square, soft square or squoval explicitly; the corner shape changes the result.', 'Very sharp corners may catch during daily wear, while squoval softens them.'),
  post('wedding-nail-art-ideas', 'Wedding Nail Art Ideas for UK Brides', 'wedding nail art ideas', 'Shapes', 'Refined bridal ideas plus a sensible trial, photography and appointment checklist.', 'Glamour UK', 'https://www.glamourmagazine.co.uk/gallery/wedding-nails', 21,
    [['Milky micro-French', 'A fine white edge photographs cleanly without dominating.'], ['Pearl accent', 'One small pearl nods to jewellery and fabric texture.'], ['Veil linework', 'Fine white botanical or lace detail can echo the outfit.'], ['Tonal shimmer', 'Low-contrast sparkle catches light in close-up photographs.'], ['Signature red', 'A classic red can feel bridal when it is already part of your style.']],
    'Trial the colour and shape before the wedding, then photograph it beside the dress fabric and jewellery.', 'Stay true to your usual style rather than choosing a manicure only because it is labelled bridal.'),
  post('office-friendly-nail-art', 'Office-Friendly Nail Art That Feels Personal', 'office nail art designs', 'Shapes', 'Low-contrast ideas for varied workplaces, with no assumption that every office has the same dress code.', 'Who What Wear UK', 'https://www.whowhatwear.com/uk/nude-nail-designs', 22,
    [['Sheer gloss', 'A translucent neutral gives the neatest minimal effect.'], ['Olive micro-tip', 'An almost-neutral colour adds personality at the edge.'], ['Tonal dot', 'Place a small brown or burgundy dot over beige.'], ['Side stripe', 'One soft grey line creates detail without high contrast.'], ['Short squoval', 'A practical shape works comfortably for typing.']],
    'Check any workplace policy, then choose the level of contrast and texture that suits your role.', '“Professional” is contextual; this guide offers options rather than rules.'),
  post('how-to-choose-a-nail-shape', 'How to Choose a Nail Shape for Your Design', 'how to choose a nail shape', 'Shapes', 'A visual decision guide based on present length, natural nail plate, lifestyle and design space.', 'British Vogue', 'https://www.vogue.co.uk/article/short-nails-ideas', 23,
    [['Round', 'Practical at short lengths and follows a naturally curved tip.'], ['Oval', 'Uses a little more length for a softly elongated effect.'], ['Squoval', 'Combines a straighter edge with softened corners.'], ['Square', 'Creates a crisp edge and strong geometric canvas.'], ['Almond', 'Needs enough length to taper into a balanced point.']],
    'Choose the shape before the design so artwork can be scaled and positioned correctly.', 'Avoid rigid “best shape for your hand” rules; comfort and maintenance matter more.'),
  post('french-tip-nail-art-designs', 'French Tip Nail Art: Classic, Micro and Colourful', 'French tip nail art designs', 'Techniques', 'A visual taxonomy of French designs for short nails, events, colour lovers and minimalists.', 'Woman & Home', 'https://www.womanandhome.com/beauty/short-french-tip-nail-designs/', 24,
    [['Classic', 'A sheer neutral and clean white smile line remain timeless.'], ['Micro', 'Use the finest possible edge on a short nail.'], ['Coloured', 'Keep the base consistent while changing tip colour.'], ['Metallic', 'A chrome or gold edge gives a jewellery-like effect.'], ['Side French', 'Move the line diagonally to create an asymmetric detail.']],
    'Specify tip thickness, curve, colour and whether you want an opaque or sheer base.', 'A thick tip can visually shorten a compact nail bed.'),
  post('what-are-biab-nails', 'BIAB Nails Explained for UK Clients', 'what are BIAB nails', 'Techniques', 'A plain-English guide to the trademarked service, builder gel terminology, maintenance and safety questions.', 'The GelBottle', 'https://help.thegelbottle.com/support/solutions/articles/202000060569-what-is-biab-', 25,
    [['What it is', 'BIAB is The GelBottle’s Builder In A Bottle product range.'], ['Overlay', 'Builder gel can add structure over the natural nail without adding length.'], ['Extension', 'Some systems may also be used with forms or tips by trained professionals.'], ['Maintenance', 'Service timing and infill suitability depend on growth and product condition.'], ['Design', 'Colour, French, chrome and small art can be placed over a suitable structured base.']],
    'Ask which exact builder system is being used, how it is cured and how it should be removed.', 'Uncured acrylate product should not touch skin; allergy concerns need qualified medical advice.'),
  post('cat-eye-nail-art-designs', 'Cat-Eye Nail Art: Velvet, Halo and Line Effects', 'cat eye nail art designs', 'Techniques', 'Magnetic nail looks explained by effect, colour and the salon wording needed to distinguish them.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/cat-eye-polka-dot-tutorial/', 26,
    [['Velvet diffusion', 'A broad soft glow resembles plush fabric under moving light.'], ['Sharp line', 'A narrow diagonal highlight creates the classic cat-eye.'], ['Halo', 'Light is concentrated centrally with a darker perimeter.'], ['Magnetic French', 'The shifting pigment is limited to the tip.'], ['Dotted overlay', 'Simple dots add a graphic layer over the moving shimmer.']],
    'Name the desired magnetic pattern as well as the base colour; show how soft or sharp the highlight should be.', 'Magnetic gel requires correct curing and professional product handling.'),
  post('easy-flower-nail-art-tutorial', 'Easy Flower Nail Art Tutorial', 'easy flower nail art', 'Techniques', 'One beginner dot-flower method expanded into several wearable variations.', 'Scratch Magazine', 'https://www.scratchmagazine.co.uk/nail_art/simple-speedy-steps-floral-nail-art/', 27,
    [['Make the petals', 'Place three to five dots close together in a ring.'], ['Shape gently', 'For pointed petals, drag each wet dot slightly towards the centre.'], ['Add the centre', 'Use one small contrasting dot after the petals are stable.'], ['Vary placement', 'Try one corner flower, a French cluster or scattered micro blooms.'], ['Finish', 'Seal fully dry regular polish with a floating top-coat stroke.']],
    'Use a simple two-colour flower first, then vary size and placement once the motion feels controlled.', 'Do not press hard with the dotting tool; the product, not pressure, should form the dot.'),
  post('gel-vs-acrylic-nails-for-nail-art', 'Gel vs Acrylic Nails for Nail Art', 'gel vs acrylic nails', 'Techniques', 'A neutral comparison of application, structure, design use, upkeep, removal and UK allergy guidance.', 'British Association of Dermatologists', 'https://www.bad.org.uk/dermatologists-issue-warning-about-uk-artificial-nail-allergy-epidemic', 28,
    [['Gel systems', 'Gel and gel polish require the matched curing process specified by the manufacturer.'], ['Acrylic systems', 'Liquid and powder combine and harden in air to create structure.'], ['Design flexibility', 'Both can support art; the best choice depends on length, structure and service plan.'], ['Removal', 'Removal differs by product and should never rely on peeling.'], ['Allergy questions', 'Ask how skin contact is prevented and products are cured or handled.']],
    'Choose a trained technician based on consultation, hygiene and system knowledge—not only the finished photograph.', 'This comparison is general information, not diagnosis or individual medical advice.'),
  post('nail-care-before-after-nail-art', 'Nail Care Before and After Nail Art', 'nail care before and after nail art', 'Techniques', 'Evidence-led general care for preparation, wear and removal, including signs that need professional advice.', 'NHS', 'https://www.nhs.uk/symptoms/nail-problems/', 29,
    [['Before', 'Keep nails clean, gently shaped and free from active soreness.'], ['During wear', 'Use gloves when hands spend time in water or cleaning products.'], ['Moisturise', 'Apply hand cream to nails and fingertips regularly.'], ['Remove carefully', 'Follow the product’s removal method rather than picking or scraping.'], ['Know when to ask', 'Unexplained colour or shape change, separation or inflamed skin warrants advice.']],
    'Tell your technician about existing sensitivity or previous reactions before any product is applied.', 'Nail problems can have many causes; consult a GP or podiatrist when NHS guidance recommends it.'),
];

export function getBlogPost(slug: string) {
  return blogPosts.find((item) => item.slug === slug);
}

export function getRelatedBlogPosts(current: BlogPost) {
  const sameCategory = blogPosts.filter((item) => item.slug !== current.slug && item.category === current.category);
  const others = blogPosts.filter((item) => item.slug !== current.slug && item.category !== current.category);
  return [...sameCategory, ...others].slice(0, 3);
}
